pndroa/event-planer

- docs/routes.md
- package-lock.json
- package.json
- src/app/event/[id]/page.tsx
- src/app/event/create/page.tsx
- src/app/event/create/survey/page.tsx
- src/app/event/myEvent/[id]/edit/page.tsx
- src/app/event/myEvent/[id]/page.tsx
- src/app/event/myEvent/page.tsx
- src/app/event/mySurvey/page.tsx
- src/app/event/page.tsx
- src/app/login/page.tsx
- src/app/page.tsx
- src/app/registration/page.tsx
- src/app/wish/[id]/page.tsx
- src/app/wish/myWish/[id]/[edit]/page.tsx
- src/app/wish/myWish/[id]/page.tsx
- src/app/wish/myWish/page.tsx
- src/app/wish/page.tsx
Directory structure for Event-Planer app.
> Directory structure added to project.

- .env.template
- src/lib/api.ts
added config file for axios instance
> Scrum 58 front backend schnittstelle erstellen

- package-lock.json
- package.json
- prisma/schema.prisma
define and push Prisma schema changes
> feat: create pull request

- .eslintrc.json
- .github/workflows/nextjs.yml
- .prettierrc
- next.config.mjs
- package-lock.json
- package.json
- src/app/layout.tsx
- tsconfig.json
created eslint and prettier config
> Scrum 60 coding guidelines erstellen

- .vscode/settings.json
- docs/javascript-snippets.md
- docs/typescript-snippets.md
- package-lock.json
- package.json
- src/app/layout.tsx
- src/components/Navbar.tsx
Added Global Navbar and Appbar for users to Navigate between the pages. Added mobile friendly view.
> feat: add a global Navbar and Appbar

- src/app/api/wish/route.ts
- src/app/wish/page.tsx
- src/components/Navbar.tsx
- src/utils/serializeWish.ts
Implemented the wishes feed page with initial API integration. Includes serialization of API response and basic UI layout with Material UI. 
- GET request to fetch wishes from backend 
- Serialization of wish data including user info 
- Responsive and styled wishes feed using MUI components 
- Placeholder for "Create Wish" button 
- Likes are currently non-interactive
> Add wishes feed page with API integration and serialization

- src/app/layout.tsx
- src/components/Navbar.tsx
Since the customer was not satisfied with the previous Navbar and AppBar implementation, this version replicates the design from the Balsamiq mockup.
> fix: adjusted global nav and appbar according to customer feedback

- src/app/api/wish/[wishid]/upvote/route.ts
- src/app/api/wish/route.ts
- src/app/wish/page.tsx
- src/components/WishCard.tsx
- src/lib/types.ts
Add Upvote Feature suitable with the changes made by Baran and Erguen
> feat: add upvote Feature

- src/app/event/page.tsx
- src/components/TopNavigation.tsx
changed My Event Feed to a button which filters the events to my events
> feat: add my Events filter

- src/app/api/event/[id]/route.ts
- src/app/event/myEvent/[id]/edit/page.tsx
- src/app/event/mySurvey/page.tsx
- src/components/datePicker.tsx
- src/lib/types.ts
- src/lib/validation.ts
(feat): Update Events feature implemented, able to update title, description, room and the dates
> (feat): Update Events feature

- src/app/api/event/route.ts
- src/app/api/wish/[id]/route.ts
- src/app/api/wish/myWish/[id]/route.ts
- src/app/api/wish/route.ts
- src/app/event/create/page.tsx
- src/app/event/page.tsx
- src/app/wish/myWish/page.tsx
- src/app/wish/page.tsx
- src/components/EventCard.tsx
- src/components/SelectedEventCard.tsx
- src/components/SelectedMyWishesCard.tsx
- src/components/SelectedWishCard.tsx
- src/components/WishCard.tsx
- src/lib/types.ts
- src/lib/validation.ts
1. Detail view via backdrop instead of routing:
=> Implemented overlay-style detail views (backdrop) for wishes and events without using [id]/page.tsx routes
=> Affected pages: app/(app)/eventfeed/page.tsx, app/(app)/wishfeed/page.tsx, app/(app)/mywishes/page.tsx
2. Wish-to-Event conversion logic:
=> Added logic to prefill event creation with data from a selected wish
=> On conversion, the corresponding wish is flagged as converted
3. Model update (event):
=> Added new field wishId to store the originating wish reference in the event
4. Wish filtering:
=> Filtered out wishes that are already converted (isConvertedToEvent: true) in the wishfeed
5. New components: selectedWishCard.tsx, selectedMyWishCard.tsx, selectedEventCard.tsx
> SCRUM-30-Wuensche-in-Events-umwandeln

- prisma/schema.prisma
- src/app/api/event/[id]/route.ts
- src/app/event/myEvent/[id]/edit/page.tsx
- src/components/EventCard.tsx
- src/components/deleteOverlay.tsx
(feat): Deleting events from database
> (feat): Delete event from Database

- src/app/api/event/route.ts
- src/app/api/survey/route.ts
- src/app/api/survey/surveyAnswerOption/route.ts
- src/app/api/survey/surveyAnswers/[id]/route.ts
- src/app/api/survey/surveyAnswers/route.ts
- src/app/api/survey/surveyQuestion/[id]/route.ts
- src/app/api/survey/surveyQuestion/route.ts
- src/app/event/[id]/survey/edit/page.tsx
- src/app/event/[id]/survey/page.tsx
- src/app/event/create/[id]/survey/page.tsx
- src/app/layout.tsx
- src/components/surveyForm.tsx
- src/middleware.ts
Update and edit questions in a survey
> Scrum 25 surveys bereits erstellte fragen zu meinem event bearbeiten

- src/app/api/wish/[id]/route.ts
- src/app/api/wish/[id]/upvote/route.ts
- src/app/wish/[id]/page.tsx
- src/app/wish/page.tsx
Added delete button on dynamic wish page
> Scrum 108 meine erstellten wuensche loeschen

- src/app/api/event/[id]/route.ts
- src/app/api/event/route.ts
- src/app/event/[id]/page.tsx
- src/app/event/[id]/survey/page.tsx
- src/app/event/myEvent/[id]/edit/page.tsx
- src/app/event/page.tsx
- src/components/EventCard.tsx
- src/components/deleteOverlay.tsx
- src/lib/eventParticipationService.ts
- src/utils/timeUtils.ts
=> Features implemented:
1. Auto-Add Participants from Wish Likes
- Users who liked a wish are automatically added as participants when that wish is converted to an event.
- Triggered only when a wishId is provided during event creation.
- Participation logic is encapsulated in a dedicated service function.
2. New Event Detail Page
- Added dynamic route: event/[id]/page.tsx
- Displays title, date/time, location, description, and organizer.
- Moved all relevant buttons (Edit, Delete, View Survey) to this page.
3. Add Questions to Existing Survey
- Button "View Survey" visible for own events on the detail page.
- Navigates to survey overview.
- Button "+ Create Question" allows adding new questions to the existing survey (one survey per event).
> Scrum 35 fragen zu einer bestehenden survey eines eigenen events hinzufuegen

- src/app/event/[id]/survey/page.tsx
- src/app/event/mySurvey/page.tsx
- src/components/header.tsx
> (Bug): Removed profile-button

- src/app/event/[id]/survey/page.tsx
- src/app/event/mySurvey/page.tsx
Change surveyId to eventId, in route
> (Bug): Changed surveyId to eventId, in Route

- src/components/datePicker.tsx
> Scrum 113 datumeingabe auf englisch aber datum format auf deutsch

- src/app/wish/create/page.tsx
(bug): "Create Wish" Button disables again after input in Title is incorrect again
> SCRUM-112-Keine-Wishes-mit-Blankspace-als-Title

- package-lock.json
- package.json
- prisma/schema.prisma
- src/app/api/notifications/[id]/route.ts
- src/app/api/notifications/route.ts
- src/app/api/survey/route.ts
- src/app/api/survey/surveyQuestion/route.ts
- src/app/event/[id]/statistics/page.tsx
- src/components/header.tsx
- src/lib/types.ts
Added Notification Handler and used it for Surveys, so everytime a survey is created or a question is added the participants get a notification
> Scrum 95 in app benachrichtigung

- src/app/event/create/page.tsx
(bug) rerouting after creating an event
> SCRUM-133-Nach-Event-Erstellung-auf-events-weiterleiten-statt-zu-Survey

- src/components/surveyAnswerCard.tsx
(bug) removed,  undo button from edit answer survey enabled change on click
> SCRUM-150-Survey-questions-beantworten-kein-edit-button

- src/components/surveyForm.tsx
(bug): radio and delete button move with date and text field when error message is shown.
> SCRUM-151-CreateSurveyCard-Radio-button-nicht-aligned-mit-Eingabe

- __tests__/unitTests/getUserTest.ts
- __tests__/unitTests/timeUtilsTest.ts
> Scrum-126-unit-tests-erstellen

- public/emailTemplates/eventEmail.ejs
- src/app/api/event/[id]/route.ts
- src/app/api/event/route.ts
- src/app/event/myEvent/[id]/edit/page.tsx
- src/components/timePicker.tsx
- src/lib/eventParticipationService.ts
Minor bug fix empty TimePicker's aren't surounded red anymore and code cleanup deleted unused code
> Scrum-92-code-clean-up-aus-lagern-von-unnoetigem-code
